---
platform: linux

image_resource:
  type: docker-image
  source: {repository: python, tag : latest}

inputs:
  - name: resource-tutorial
#    path: gopath/src/github.com/cloudfoundry-community/simple-go-web-app

jobs:
- name: job
  plan:
  - task: install-packages
    config:
      platform: linux
      run:
        path: pip
        args: ["install", "openpyxl"]
  - task: run-script
    config:
      inputs:
        - name: resource-tutorial
      platform: linux
      run:
        path: python
        args: [resource-tutorial/hello.py]
        
#run:
#  path: /bin/sh
#  args:
#    - resource-tutorial/build_script.sh

#    - -c
#    - pip install requests

#  path: pip
#  args: ["install", "openpyxl"]

#  path: python
#  args: [resource-tutorial/hello.py]

